services:
  postgres:
    image: postgres:16
    networks:
      default:
        aliases:
          - postgresLocalServer_Project
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_web
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres
  
  backend_dev : 
    build : . # contruit le contenaire  a partir de mon docker file ./DockerFile
    container_name: Project_Django_Dev
    image : dev_env
    volumes: # acces au code dans le container depuis mon dossier project
      - ./backend:/app_dev
    ports : 
      - "8000:8000"
    depends_on : 
      - postgres
    # pour mon terminal de dev pour interagir avec le bash lancer dans le docker file 
    stdin_open : true
    tty : true 

